version: '3.8'  # version de Docker Compose utilisée

services:
  web:  # Définition du service pour l'application web FastAPI
    build: .  # Indique à Docker de construire l'image à partir du Dockerfile situé dans le répertoire actuel
    ports:
      - "8000:8000"  # Mappe le port 8000 de l'hôte au port 8000 du conteneur pour accéder à l'application web
    environment:
      DATABASE_URL: mysql+pymysql://root:@host.docker.internal/Item-docker-api  # Définit la variable d'environnement pour la connexion à la base de données
    depends_on:
      - db  # Assure que le service 'web' démarre après le service 'db'

  db:  # Définition du service pour la base de données MySQL
    image: mysql:8.0  # Utilise l'image MySQL version 8.0
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_DATABASE: Item-docker-api  
      MYSQL_USER: root  
      MYSQL_PASSWORD:  
    ports:
      - "3307:3306"  # Mappe le port 3307 de l'hôte au port 3306 du conteneur pour accéder à MySQL (corrigé pour utiliser le port MySQL par défaut 3306)
    volumes:
      - mysql_data:/var/lib/mysql  # Monte un volume pour persister les données de la base de données

volumes:
  mysql_data:  # Déclare un volume nommé 'mysql_data' pour stocker les données de MySQL
